apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: otel
  labels:
    app: otel-collector
    component: otel-collector-config
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:
      memory_limiter:
        limit_mib: 1500
        spike_limit_mib: 512
        check_interval: 5s

    exporters:
      otlp:
        endpoint: "http://elastic-apm-server.elastic-system.svc:4317"
        tls:
          insecure: true
      debug: {}

    extensions:
      zpages: {}

    service:
      extensions: [zpages]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp,debug]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp,debug]