apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-agent-config
  namespace: otel
data:
  otel-agent-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:

    exporters:
      otlp:
        endpoint: otel-collector.otel.svc.cluster.local:4317
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]